version: "3.8"

services:
  backend:
    build: .
    container_name: graphql_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=bookstore
      - MONGO_URI=mongodb://mongo:27017/bookstore?replicaSet=rs0
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start"

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
