
services:
  backend:
    build: .
    container_name: graphql_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo1
      - mongo2
    environment:
      - MONGO_HOST=mongo1
      - MONGO_PORT=27017
      - MONGO_DB=bookstore
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017/bookstore?replicaSet=rs0
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start"

volumes:
  mongo1_data:
  mongo2_data:

networks:
  mongo:
    driver: bridge

  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo


