
services:
  backend:
    build: .
    container_name: graphql_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - .env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    command: sh -c "npx prisma generate && npm run start"

  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo

volumes:
  mongo1_data:
  mongo2_data:

networks:
  mongo:
    driver: bridge
