services:
  backend:
    build: .
    container_name: graphql_backend_rs
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo:6
    container_name: mongo1_rs
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - app-net

  nginx:
    image: nginx:mainline-alpine
    container_name: WebDemoSeverGraphQL
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
